### ISSUE TITLE
Upgrade to Django 4.2 in Open Notificaties

### ISSUE THREAD

**Issue by Viicos** [open-zaak/open-notificaties#124]
Dependencies:
- [x] `django-auth-adfs-db`: unsupported, but seems to not be relevant anymore? See `uninstall_adfs.sh`
- [x] `django-axes`: can be updated, some settings were deprecated. See https://github.com/open-formulieren/open-forms/commit/73ea9d739bae2ecf4d6fa8e91090cc4a708ebe0a for an example
- [x] `django-choices`: not used, can be removed
- [x] `django-cors-headers`: can be updated
- [x] `django-markup`: can be removed? I don't see any references in the code
- [x] `django-redis`: can be updated
- [x] `django-admin-index`: can be updated, iirc some changes are needed
- [x] `mozilla-django-oidc-db`: can be updated, need to check changelog 
- [x] `django-log-outgoing-requests`: can be updated, check this [breaking change](https://github.com/maykinmedia/django-log-outgoing-requests/blob/main/CHANGELOG.rst#050-2023-08-15) before
- [ ] `gemma-zds-client`: Should be updated to 2.x, so that `zgw-consumers` can also be bumped.
- [ ] `drf-yasg`: should switch to `drf-spectacular`, requires some work

Deprecation warnings:

- [ ] A bunch of deprecation warnings related to ZDS: in particular, the use of the mock client. Should probably switch to the ape pie client but requires some work.
- [x] `django-relativedelta` makes use of `uget*`; should be fixed by upgrading `zgw-consumers`.

**Comment by sergei-maertens** [comment]
* django-markup is used in the commonground-api-common templates afaik! Please double check before removing it, since I remember there not being tests that would catch the accidental removal.
* django-admin-index requires some changes to the admin overrides CSS, see also the remarks in https://github.com/maykinmedia/open-klant/issues/130
* I don't see drf-yasg in the list, I expect big problems there (it's a dependency of commonground-api-common). This commonground-api-common in general is problematic.

**Comment by Viicos** [comment]
> I don't see drf-yasg in the list, I expect big problems there (it's a dependency of commonground-api-common). This commonground-api-common in general is problematic.

It's in the deprecation  warnings list, but I'll add it to the main list
