### ISSUE TITLE
abonnement filter key stored as snake_case

### ISSUE THREAD

**Issue by paul-ritense** [open-zaak/open-notificaties#171]
In the Notifications API when updating an abonnement the key in the filters is stored as snake_case. 
objectType is stored as object_type, while filtering on objecttype only works with objectType in camelCase.
Steps to reproduce:
- Update an abonnement by adding objectType filters to the object channel
- In the UI the filter key is object_key and the filter does not work
- Update the object_type to objectType in the UI
- Now the objectType filter works.

See an example [notifications_API.txt](https://github.com/user-attachments/files/16106996/notifications_API.txt) with curl in the attachment.

**Comment by joeribekker** [comment]
This ticket was approved by DH so it can be picked up.

**Comment by JanBrek** [comment]
@joeribekker Any estimation for when this will be picked up?

**Comment by joeribekker** [comment]
It will be discussed tomorrow, I know more by then

**Comment by joeribekker** [comment]
So, the tasks here are:

* [ ] Make the `register_kanalen` command work in the Objects API (https://github.com/maykinmedia/objects-api/issues/426)
* [ ] Make sure the channel filter is registered as "objectType"
* [ ] Make the Notifications page work and informative. In Open Zaak we link to the VNG reference implementation text file (like here: https://github.com/VNG-Realisatie/zaken-api/blob/stable/1.0.x/src/notificaties.md). I think we should grab this file and include it (again) in our repo's, but for now lets just do this for Objects API (see: https://objecten.demo.opengem.nl/) Notifications button that it doesnt work now. Let's just have it link to the MD file like Open Zaak.

**Comment by annashamray** [comment]
This bug happens because of inconsistency of using camelCase and snake_case in 3 places:
* kanaal filters
* abonnement filters
* notification filters

**As is**:
1. In the Objects API: when we register a kanaal (with `register_kanalen` management command) it's created with name `objecten` and kenmerken `["object_type"]`
2. In the Notifications: when we create or update an abonnement via API it's filters are always converted to snake_case, i.e. even if it's created with  `"filters" : {"objectType": <some-url>}, the filter will be saved as `object_type`
3. In the Objects API: when an object is created, the notification is sent with `"kenmerken": {"objectType":  <some-url>}`, because Objects API camelizes the notification message before sending it to Notifications API

And then Notifications API can't match abonnement,filters and notification,kenmerken

**Possible solutions**
1. Leave everython as it is, and just improve matching in Notifications API, so it could process and compare both camelCase and snake_case. I think it's the easiest solution, which won't affect much.

2. Make everythinh cameCase as Joeri suggested. In this case we will have to make quite a lot of changes including data migrations: 
  *  Objecttypes API: create kanaal with  kenmerken `["objectType"]`
  * Notifications API: make data migration to change existing `objecten` kanaal
  * Notifications API: save Abonnementen filters with camelCase (this one is quite tricky to be honest, I don't know how to do it easily without switching renderer and parser) 
  * Notifications API: make data migration to change existing abonnementen filters

Which one should we choose? 
@joeribekker @alextreme Could you help me please?

**Comment by alextreme** [comment]
@annashamray considering the impact of Joeri's suggestion lets go with the first solution you suggested.
